# Generated by Django 3.1.4 on 2021-04-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helps',
            name='name',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='helps',
            name='city',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='helps',
            name='help',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='helps',
            name='state',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
