# Generated by Django 3.1.4 on 2021-04-24 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210424_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helps',
            old_name='help',
            new_name='helps',
        ),
    ]
