# Generated by Django 3.1.4 on 2021-05-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='delete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkCode', models.IntegerField()),
                ('reason', models.CharField(max_length=100000)),
            ],
        ),
    ]
