# Generated by Django 3.1.4 on 2021-05-17 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='delete',
            new_name='Ndelete',
        ),
    ]
