# Generated by Django 3.1.4 on 2021-05-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210517_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helps',
            name='contact',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
